#!/usr/bin/env npx zx
/**
 * Generate Glance configuration from server definitions
 * Usage: zx generate-glance.mts
 */

import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { stringify } from "yaml";
import { createGlanceConfig } from "../configs/glance/glance.template.mts";
import { log } from "./lib.mts";
import { servers } from "./servers.mts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoDir = dirname(__dirname);
const outputPath = join(repoDir, "configs/glance/glance.yml");

const config = createGlanceConfig(servers, servers.ad);

const header = `# Glance Dashboard Configuration
# https://github.com/glanceapp/glance/blob/main/docs/configuration.md
#
# Generated by: zx generate-glance.mts
# Sync to container: just sync-glance
# Auto-reloads on save (no container restart needed)

`;

const yaml = stringify(config, { lineWidth: 0 });

await writeFile(outputPath, header + yaml);

log.ok(`Generated ${outputPath}`);
